CREATE TABLE USERINFO( USERNAME VARCHAR (50) NOT NULL,USERADDRESS VARCHAR (50) NOT NULL,USEREMAIL VARCHAR (50) NOT NULL, PASS VARCHAR (50) NOT NULL,USERPHONE NVARCHAR (50) NOT NULL, ) 
SELECT* FROM USERINFO;
Drop Table Userinfo;
